version: '3.9'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env
    container_name: isaac-web
    networks:
      - default
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    container_name: isaac-api
    networks:
      - default
    ports:
      - 5001:5001
    volumes:
        - ./api:/app

networks:
  default:
    name: isaac-network
