version: '3.9'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env.example
    ports:
      - 3000:3000

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY= # your openai api key
    ports:
      - 5001:5001
