import type { EditorThemeClasses } from 'lexical';

const defaultTheme: EditorThemeClasses = {
	ltr: 'ltr',
	rtl: 'rtl',
	// placeholder: 'editor-placeholder',
	paragraph: 'editor-paragraph',
	quote: 'editor-quote',
	heading: {
		h1: 'editor-heading-h1',
		h2: 'editor-heading-h2',
		h3: 'editor-heading-h3',
		h4: 'editor-heading-h4',
		h5: 'editor-heading-h5',
		h6: 'editor-heading-h6',
	},
	list: {
		listitem: 'DefaultTheme__listItem',
		listitemChecked: 'DefaultTheme__listItemChecked',
		listitemUnchecked: 'DefaultTheme__listItemUnchecked',
		nested: {
			listitem: 'DefaultTheme__nestedListItem',
		},
		olDepth: [
			'DefaultTheme__ol1',
			'DefaultTheme__ol2',
			'DefaultTheme__ol3',
			'DefaultTheme__ol4',
			'DefaultTheme__ol5',
		],
		ul: 'DefaultTheme__ul',
	},
	image: 'editor-image',
	link: 'editor-link',
	text: {
		bold: 'editor-text-bold',
		italic: 'editor-text-italic',
		// overflowed: 'editor-text-overflowed',
		// hashtag: 'editor-text-hashtag',
		underline: 'editor-text-underline',
		strikethrough: 'editor-text-strikethrough',
		underlineStrikethrough: 'editor-text-underlineStrikethrough',
		code: 'editor-text-code',
	},
	code: 'editor-code',
	codeHighlight: {
		atrule: 'editor-tokenAttr',
		attr: 'editor-tokenAttr',
		boolean: 'editor-tokenProperty',
		builtin: 'editor-tokenSelector',
		cdata: 'editor-tokenComment',
		char: 'editor-tokenSelector',
		class: 'editor-tokenFunction',
		'class-name': 'editor-tokenFunction',
		comment: 'editor-tokenComment',
		constant: 'editor-tokenProperty',
		deleted: 'editor-tokenProperty',
		doctype: 'editor-tokenComment',
		entity: 'editor-tokenOperator',
		function: 'editor-tokenFunction',
		important: 'editor-tokenVariable',
		inserted: 'editor-tokenSelector',
		keyword: 'editor-tokenAttr',
		namespace: 'editor-tokenVariable',
		number: 'editor-tokenProperty',
		operator: 'editor-tokenOperator',
		prolog: 'editor-tokenComment',
		property: 'editor-tokenProperty',
		punctuation: 'editor-tokenPunctuation',
		regex: 'editor-tokenVariable',
		selector: 'editor-tokenSelector',
		string: 'editor-tokenSelector',
		symbol: 'editor-tokenProperty',
		tag: 'editor-tokenProperty',
		url: 'editor-tokenOperator',
		variable: 'editor-tokenVariable',
	},
	table: 'PlaygroundEditorTheme__table',
	tableAddColumns: 'PlaygroundEditorTheme__tableAddColumns',
	tableAddRows: 'PlaygroundEditorTheme__tableAddRows',
	tableCell: 'PlaygroundEditorTheme__tableCell',
	tableCellActionButton: 'PlaygroundEditorTheme__tableCellActionButton',
	tableCellActionButtonContainer:
		'PlaygroundEditorTheme__tableCellActionButtonContainer',
	tableCellEditing: 'PlaygroundEditorTheme__tableCellEditing',
	tableCellHeader: 'PlaygroundEditorTheme__tableCellHeader',
	tableCellPrimarySelected: 'PlaygroundEditorTheme__tableCellPrimarySelected',
	tableCellResizer: 'PlaygroundEditorTheme__tableCellResizer',
	tableCellSelected: 'PlaygroundEditorTheme__tableCellSelected',
	tableCellSortedIndicator: 'PlaygroundEditorTheme__tableCellSortedIndicator',
	tableResizeRuler: 'PlaygroundEditorTheme__tableCellResizeRuler',
	tableSelected: 'PlaygroundEditorTheme__tableSelected',
};

export default defaultTheme;
