import {
	Book,
	BookMarked,
	BookOpen,
	BookPlus,
	BookUpIcon,
	File,
	FileBadge,
	FileBarChart,
	FileText,
	FileType2,
	Film,
	Gavel,
	Globe2,
	LucideIcon,
	Mic,
	Newspaper,
	Receipt,
} from 'lucide-react';
import { ReferenceType } from 'types/literatureReference.type';

export const ReferenceTypeIconsMap: Record<ReferenceType, LucideIcon> = {
	[ReferenceType.UNSPECIFIED]: File,
	[ReferenceType.JOURNAL]: Book,
	[ReferenceType.ARTICLE]: FileText,
	[ReferenceType.WEB_PAGE]: Globe2,
	[ReferenceType.BOOK]: Book,
	[ReferenceType.BOOK_SECTION]: BookOpen,
	[ReferenceType.THESIS]: BookMarked,
	[ReferenceType.NEWSPAPER]: Newspaper,
	[ReferenceType.FILM]: Film,
	[ReferenceType.BILL]: Receipt,
	[ReferenceType.HEARING]: Gavel,
	[ReferenceType.CONFERENCE]: Mic,
	[ReferenceType.REPORT]: FileBarChart,
	[ReferenceType.PATENT]: FileBadge,
	[ReferenceType.STANDARD]: FileType2,
	[ReferenceType.USER_UPLOAD]: BookUpIcon,
};
